## Yield Curve Fitting

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

### 1. Data Preparation & Cleaning

In [2]:
## If cleaned data is available, read cleaned data directly
## Else, read raw data and clean it
read_raw_data = True

In [3]:
if read_raw_data:
    ## Read raw data
    yield_raw = pd.read_csv('../data/yield.csv')
    yield_raw['Date'] = pd.to_datetime(yield_raw['Date'])

    ## Cleaning raw
    ## Get rid of data before 07/30/01 since older data had no 1 MO yield data
    yield_cleaned = yield_raw.loc[yield_raw['Date']>'2001-07-30'].reset_index(drop = True)
    ## Also get rid of 2020 data since it is our target
    yield_cleaned = yield_cleaned.loc[yield_cleaned['Date']<'2020-01-01'].reset_index(drop = True)
    ## If no 30 YR yield data, use the 20 YR yield data, since they are highly related 
    ## (See Abramov et. al.)
    yield_cleaned.loc[:,'30 YR'] = [i[1] if i[2] == 0 else i[2] 
                                    for i in yield_cleaned.loc[:,['20 YR', '30 YR']].itertuples()]
    ## Get rid of 2 MO yields since it was not introduced until late 2018
    yield_cleaned = yield_cleaned.drop('2 MO', axis = 1)
    ## Save for late use
    yield_cleaned.to_csv('../data/yield_cleaned.csv', index = False)
else:
    yield_cleaned = pd.read_csv('../data/yield_cleaned.csv')
    yield_cleaned['Date'] = pd.to_datetime(yield_cleaned['Date'])

In [4]:
## Examplar cleaned data
yield_cleaned.head(5)

Date  1 MO  3 MO  6 MO  1 YR  2 YR  3 YR  5 YR  7 YR  10 YR  20 YR  \
0 2001-07-31  3.67  3.54  3.47  3.53  3.79  4.06  4.57  4.86   5.07   5.61   
1 2001-08-01  3.65  3.53  3.47  3.56  3.83  4.09  4.62  4.90   5.11   5.63   
2 2001-08-02  3.65  3.53  3.46  3.57  3.89  4.17  4.69  4.97   5.17   5.68   
3 2001-08-03  3.63  3.52  3.47  3.57  3.91  4.22  4.72  4.99   5.20   5.70   
4 2001-08-06  3.62  3.52  3.47  3.56  3.88  4.17  4.71  4.99   5.19   5.70   

   30 YR  
0   5.51  
1   5.53  
2   5.57  
3   5.59  
4   5.59

In [5]:
## Cleaned data summary statistics
yield_cleaned.describe()

1 MO         3 MO         6 MO         1 YR         2 YR  \
count  4606.000000  4606.000000  4606.000000  4606.000000  4606.000000   
mean      1.297451     1.353608     1.466077     1.577794     1.823517   
std       1.485886     1.508155     1.536025     1.498917     1.413028   
min       0.000000     0.000000     0.020000     0.080000     0.160000   
25%       0.070000     0.100000     0.160000     0.270000     0.640000   
50%       0.900000     0.950000     1.040000     1.220000     1.480000   
75%       1.967500     2.010000     2.130000     2.350000     2.660000   
max       5.270000     5.190000     5.330000     5.300000     5.290000   

              3 YR         5 YR         7 YR        10 YR        20 YR  \
count  4606.000000  4606.000000  4606.000000  4606.000000  4606.000000   
mean      2.063769     2.534783     2.903291     3.235795     3.799103   
std       1.341612     1.224258     1.138802     1.075487     1.119692   
min       0.280000     0.560000     0.910000     1.370000     1.690000   
25%       0.960000     1.570000     2.000000     2.280000     2.740000   
50%       1.650000     2.320000     2.780000     3.060000     3.880000   
75%       2.907500     3.430000     3.850000     4.190000     4.810000   
max       5.260000     5.230000     5.290000     5.440000     6.050000   

             30 YR  
count  4606.000000  
mean      3.923356  
std       0.985139  
min       1.940000  
25%       3.010000  
50%       4.040000  
75%       4.770000  
max       6.050000

In [6]:
dyield = yield_cleaned.iloc[:-1, :].copy()
dy = yield_cleaned.iloc[:, 1:].values
dyield.iloc[:, 1:] = (np.vstack([dy, np.zeros(dy.shape[1])]) - np.vstack([np.zeros(dy.shape[1]), dy]))[1:-1]

In [7]:
## Examplar delta yield
dyield.head(5)

Date  1 MO  3 MO  6 MO  1 YR  2 YR  3 YR  5 YR  7 YR  10 YR  20 YR  \
0 2001-07-31 -0.02 -0.01  0.00  0.03  0.04  0.03  0.05  0.04   0.04   0.02   
1 2001-08-01  0.00  0.00 -0.01  0.01  0.06  0.08  0.07  0.07   0.06   0.05   
2 2001-08-02 -0.02 -0.01  0.01  0.00  0.02  0.05  0.03  0.02   0.03   0.02   
3 2001-08-03 -0.01  0.00  0.00 -0.01 -0.03 -0.05 -0.01  0.00  -0.01   0.00   
4 2001-08-06  0.01  0.00  0.00  0.00  0.02  0.02  0.01  0.01   0.01   0.01   

   30 YR  
0   0.02  
1   0.04  
2   0.02  
3   0.00  
4   0.01

In [8]:
## Delta yield summary statistics
dyield.describe()

1 MO         3 MO         6 MO         1 YR         2 YR  \
count  4605.000000  4605.000000  4605.000000  4605.000000  4605.000000   
mean     -0.000476    -0.000432    -0.000406    -0.000421    -0.000480   
std       0.063741     0.046204     0.037007     0.037812     0.051412   
min      -1.050000    -0.810000    -0.490000    -0.500000    -0.540000   
25%      -0.010000    -0.010000    -0.010000    -0.010000    -0.020000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.010000     0.010000     0.010000     0.010000     0.020000   
max       0.860000     0.760000     0.750000     0.520000     0.380000   

              3 YR         5 YR         7 YR        10 YR        20 YR  \
count  4605.000000  4605.000000  4605.000000  4605.000000  4605.000000   
mean     -0.000530    -0.000625    -0.000658    -0.000684    -0.000730   
std       0.055756     0.059802     0.060387     0.057272     0.054471   
min      -0.500000    -0.460000    -0.530000    -0.510000    -0.340000   
25%      -0.030000    -0.030000    -0.040000    -0.030000    -0.030000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.030000     0.030000     0.030000     0.030000     0.030000   
max       0.370000     0.340000     0.300000     0.250000     0.260000   

             30 YR  
count  4605.000000  
mean     -0.000678  
std       0.053763  
min      -0.330000  
25%      -0.030000  
50%       0.000000  
75%       0.030000  
max       0.280000

In [9]:
## Scenarios by the Fed
## baseline
baseline_q1 = np.array([1.6, 1.7, 1.8])
baseline_q2 = np.array([1.5, 1.7, 1.9])
baseline_q3 = np.array([1.5, 1.7, 1.9])
baseline_q4 = np.array([1.4, 1.8, 2.0])
baseline = np.vstack([baseline_q1, baseline_q2 ,baseline_q3,baseline_q4])
## severly adverse
sevadv_q1 = np.array([0.1, 0.5, 0.7])
sevadv_q2 = np.array([0.1, 0.6, 0.9])
sevadv_q3 = np.array([0.1, 0.6, 1.0])
sevadv_q4 = np.array([0.1, 0.7, 1.1])
sevadv = np.vstack([sevadv_q1, sevadv_q2, sevadv_q3, sevadv_q4])

## 2. Nelson-Siegel Modeling

In [10]:
## Hyperparameter (See Abramov et. al.)
lmbda = 0.0299

## slope
def I1(T, lmbda = lmbda):
    return (1-np.exp(-lmbda*T))/(lmbda*T)

## curvature
def I2(T, lmbda = lmbda):
    return (1-np.exp(-lmbda*T))/(lmbda*T) - np.exp(-lmbda*T)

In [11]:
## level, slope, curvature matrix for training
I_train = np.array([[1, I1(3), I2(3)],
                    [1, I1(60), I2(60)],
                    [1, I1(120), I2(120)]])

## for prediction
I_pred = np.array([[1, I1(t), I2(t)] for t in [1, 3, 6, 12, 24, 36, 60, 84, 120, 240, 360]])

In [12]:
## train and predict baseline scenario
betas_baseline = np.linalg.inv(I_train).dot(baseline.T)
preds_baseline = I_pred.dot(betas_baseline)

## train and predict severly adverse scenario
betas_sevadv = np.linalg.inv(I_train).dot(sevadv.T)
preds_sevadv = I_pred.dot(betas_sevadv)

In [13]:
## some reporting of results here

## 3. PCA

In [14]:
from sklearn.decomposition import PCA

In [40]:
X = yield_cleaned.iloc[:, 1:].values.T
pca = PCA(n_components = 3)
pca.fit(X)
pca.transform(X)

array([[-81.2451821 , -12.02708327,   8.00783344],
       [-78.53228432,  -9.58457948,   2.27112156],
       [-72.23841728,  -6.11045745,  -4.73924157],
       [-63.16907629,  -0.12519767,  -6.36913362],
       [-42.15848277,   9.66117964,  -4.41867822],
       [-22.13660524,  13.7644007 ,  -0.87503027],
       [ 15.83469354,  13.02743489,   3.71921131],
       [ 44.49367841,   8.69237564,   4.75944683],
       [ 69.66228054,   1.13175082,   2.54451287],
       [110.68490143,  -6.21979962,  -1.58188917],
       [118.80449409, -12.2100242 ,  -3.31815316]])

In [30]:
u, sig, wt = np.linalg.svd(X)
u[:,:3].dot(np.diag(sig[:3]))

array([[-115.79732741,  -65.71118912,   11.74444467],
       [-120.04673954,  -66.33298292,    9.58310657],
       [-128.00700895,  -65.6998955 ,    6.50782669],
       [-134.91259354,  -59.82399401,    0.5370081 ],
       [-149.62971614,  -44.80324081,   -9.39339081],
       [-163.65559167,  -30.4782954 ,  -13.63425329],
       [-190.51781652,   -3.5859934 ,  -13.08897724],
       [-210.74717809,   16.76117648,   -8.87370071],
       [-228.82810073,   34.28720644,   -1.34544283],
       [-262.20086214,   58.61613809,    6.35548584],
       [-266.01399376,   66.46598489,   12.12797705]])

In [44]:
X.dot(wt.T[:, :3])

array([[-115.79732741,  -65.71118912,   11.74444467],
       [-120.04673954,  -66.33298292,    9.58310657],
       [-128.00700895,  -65.6998955 ,    6.50782669],
       [-134.91259354,  -59.82399401,    0.5370081 ],
       [-149.62971614,  -44.80324081,   -9.39339081],
       [-163.65559167,  -30.4782954 ,  -13.63425329],
       [-190.51781652,   -3.5859934 ,  -13.08897724],
       [-210.74717809,   16.76117648,   -8.87370071],
       [-228.82810073,   34.28720644,   -1.34544283],
       [-262.20086214,   58.61613809,    6.35548584],
       [-266.01399376,   66.46598489,   12.12797705]])