## Yield Curve Fitting

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

%matplotlib inline

### 1. Data Preparation & Cleaning

In [2]:
## If cleaned data is available, read cleaned data directly
## Else, read raw data and clean it
read_raw_data = True

In [3]:
if read_raw_data:
    ## Read raw data
    yield_raw = pd.read_csv('../data/yield.csv')
    yield_raw['Date'] = pd.to_datetime(yield_raw['Date'])

    ## Cleaning raw
    ## Get rid of data before 07/30/01 since older data had no 1 MO yield data
    yield_cleaned = yield_raw.loc[yield_raw['Date']>'2001-07-30'].reset_index(drop = True)
    ## Also get rid of 2020 data since it is our target
    yield_cleaned = yield_cleaned.loc[yield_cleaned['Date']<'2020-01-01'].reset_index(drop = True)
    ## If no 30 YR yield data, use the 20 YR yield data, since they are highly related 
    ## (See Abramov et. al.)
    yield_cleaned.loc[:,'30 YR'] = [i[1] if i[2] == 0 else i[2] 
                                    for i in yield_cleaned.loc[:,['20 YR', '30 YR']].itertuples()]
    ## Get rid of 2 MO yields since it was not introduced until late 2018
    yield_cleaned = yield_cleaned.drop('2 MO', axis = 1)
    ## Save for late use
    yield_cleaned.to_csv('../data/yield_cleaned.csv', index = False)
else:
    yield_cleaned = pd.read_csv('../data/yield_cleaned.csv')
    yield_cleaned['Date'] = pd.to_datetime(yield_cleaned['Date'])

In [4]:
## Examplar cleaned data
yield_cleaned.head(5)

Date  1 MO  3 MO  6 MO  1 YR  2 YR  3 YR  5 YR  7 YR  10 YR  20 YR  \
0 2001-07-31  3.67  3.54  3.47  3.53  3.79  4.06  4.57  4.86   5.07   5.61   
1 2001-08-01  3.65  3.53  3.47  3.56  3.83  4.09  4.62  4.90   5.11   5.63   
2 2001-08-02  3.65  3.53  3.46  3.57  3.89  4.17  4.69  4.97   5.17   5.68   
3 2001-08-03  3.63  3.52  3.47  3.57  3.91  4.22  4.72  4.99   5.20   5.70   
4 2001-08-06  3.62  3.52  3.47  3.56  3.88  4.17  4.71  4.99   5.19   5.70   

   30 YR  
0   5.51  
1   5.53  
2   5.57  
3   5.59  
4   5.59

In [5]:
## Cleaned data summary statistics
yield_cleaned.describe()

1 MO         3 MO         6 MO         1 YR         2 YR  \
count  4606.000000  4606.000000  4606.000000  4606.000000  4606.000000   
mean      1.297451     1.353608     1.466077     1.577794     1.823517   
std       1.485886     1.508155     1.536025     1.498917     1.413028   
min       0.000000     0.000000     0.020000     0.080000     0.160000   
25%       0.070000     0.100000     0.160000     0.270000     0.640000   
50%       0.900000     0.950000     1.040000     1.220000     1.480000   
75%       1.967500     2.010000     2.130000     2.350000     2.660000   
max       5.270000     5.190000     5.330000     5.300000     5.290000   

              3 YR         5 YR         7 YR        10 YR        20 YR  \
count  4606.000000  4606.000000  4606.000000  4606.000000  4606.000000   
mean      2.063769     2.534783     2.903291     3.235795     3.799103   
std       1.341612     1.224258     1.138802     1.075487     1.119692   
min       0.280000     0.560000     0.910000     1.370000     1.690000   
25%       0.960000     1.570000     2.000000     2.280000     2.740000   
50%       1.650000     2.320000     2.780000     3.060000     3.880000   
75%       2.907500     3.430000     3.850000     4.190000     4.810000   
max       5.260000     5.230000     5.290000     5.440000     6.050000   

             30 YR  
count  4606.000000  
mean      3.923356  
std       0.985139  
min       1.940000  
25%       3.010000  
50%       4.040000  
75%       4.770000  
max       6.050000

In [6]:
## Get delta yields (aka change in yield rate, or shock)
dyield = yield_cleaned.iloc[:-1, :].copy()
dy = yield_cleaned.iloc[:, 1:].values
dyield.iloc[:, 1:] = (np.vstack([dy, np.zeros(dy.shape[1])]) - np.vstack([np.zeros(dy.shape[1]), dy]))[1:-1]

In [7]:
## Examplar delta yield
dyield.head(5)

Date  1 MO  3 MO  6 MO  1 YR  2 YR  3 YR  5 YR  7 YR  10 YR  20 YR  \
0 2001-07-31 -0.02 -0.01  0.00  0.03  0.04  0.03  0.05  0.04   0.04   0.02   
1 2001-08-01  0.00  0.00 -0.01  0.01  0.06  0.08  0.07  0.07   0.06   0.05   
2 2001-08-02 -0.02 -0.01  0.01  0.00  0.02  0.05  0.03  0.02   0.03   0.02   
3 2001-08-03 -0.01  0.00  0.00 -0.01 -0.03 -0.05 -0.01  0.00  -0.01   0.00   
4 2001-08-06  0.01  0.00  0.00  0.00  0.02  0.02  0.01  0.01   0.01   0.01   

   30 YR  
0   0.02  
1   0.04  
2   0.02  
3   0.00  
4   0.01

In [8]:
## Delta yield summary statistics
dyield.describe()

1 MO         3 MO         6 MO         1 YR         2 YR  \
count  4605.000000  4605.000000  4605.000000  4605.000000  4605.000000   
mean     -0.000476    -0.000432    -0.000406    -0.000421    -0.000480   
std       0.063741     0.046204     0.037007     0.037812     0.051412   
min      -1.050000    -0.810000    -0.490000    -0.500000    -0.540000   
25%      -0.010000    -0.010000    -0.010000    -0.010000    -0.020000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.010000     0.010000     0.010000     0.010000     0.020000   
max       0.860000     0.760000     0.750000     0.520000     0.380000   

              3 YR         5 YR         7 YR        10 YR        20 YR  \
count  4605.000000  4605.000000  4605.000000  4605.000000  4605.000000   
mean     -0.000530    -0.000625    -0.000658    -0.000684    -0.000730   
std       0.055756     0.059802     0.060387     0.057272     0.054471   
min      -0.500000    -0.460000    -0.530000    -0.510000    -0.340000   
25%      -0.030000    -0.030000    -0.040000    -0.030000    -0.030000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.030000     0.030000     0.030000     0.030000     0.030000   
max       0.370000     0.340000     0.300000     0.250000     0.260000   

             30 YR  
count  4605.000000  
mean     -0.000678  
std       0.053763  
min      -0.330000  
25%      -0.030000  
50%       0.000000  
75%       0.030000  
max       0.280000

In [9]:
## 12/31/2019 data to calculate shock for 2020 q1 prediction
last_date = yield_cleaned.iloc[-1, 1:].values

## Scenarios by the Fed
## baseline
baseline = np.array([1.6, 1.7, 1.8])
dbaseline = baseline - last_date[[1,6,8]]

## severly adverse
sevadv = np.array([0.1, 0.5, 0.7])
dsevadv = sevadv - last_date[[1,6,8]]

## 2. Nelson-Siegel Modeling

In [10]:
## Hyperparameter (See Abramov et. al.)
lmbda = 0.0299

## slope
def I1(T, lmbda = lmbda):
    return (1-np.exp(-lmbda*T))/(lmbda*T)

## curvature
def I2(T, lmbda = lmbda):
    return (1-np.exp(-lmbda*T))/(lmbda*T) - np.exp(-lmbda*T)

In [11]:
## level, slope, curvature matrix for training
I_train = np.array([[1, I1(3), I2(3)],
                    [1, I1(60), I2(60)],
                    [1, I1(120), I2(120)]])

## for prediction
I_pred = np.array([[1, I1(t), I2(t)] for t in [1, 3, 6, 12, 24, 36, 60, 84, 120, 240, 360]])

In [12]:
## train and predict baseline scenario
dbetas_baseline = np.linalg.inv(I_train).dot(dbaseline.T)
pred_baseline_NS = I_pred.dot(dbetas_baseline) + last_date

## train and predict severly adverse scenario
dbetas_sevadv = np.linalg.inv(I_train).dot(dsevadv.T)
pred_sevadv_NS = I_pred.dot(dbetas_sevadv) + last_date

In [13]:
pred_baseline_NS

array([1.5230875538830104, 1.6, 1.6584020333067235, 1.6590786719634811,
       1.6519165944693746, 1.6786852609697416, 1.7, 1.7841917707949355,
       1.8, 1.9922224810306481, 2.077374215563122], dtype=object)

In [14]:
pred_sevadv_NS

array([0.004083863752749162, 0.10000000000000009, 0.18530175911504254,
       0.234510408296434, 0.3067143596494424, 0.3944303054068028,
       0.49999999999999956, 0.6369084906887896, 0.6999999999999997,
       0.9523777039750234, 1.0576743117137615], dtype=object)

## 3. PCA

In [15]:
## Further set up
from sklearn import preprocessing
from sklearn.decomposition import PCA

In [16]:
## Matrix to perform PCA on
X = dyield.iloc[:, 1:].values.T

## Normalize before running PCA
## Cache the mean and sd first
X_mean = np.mean(X, axis = 1)
X_sd = np.std(X, axis = 1)

## Actual normalization
X_scaled = preprocessing.scale(X, axis = 1)

$$X = U \Sigma V^T$$ 
$$\hat{X} = U \Sigma = XV$$
$$ note: U^T = U^{-1} $$

In [17]:
## Perform SVD on the matrix
U, Sig, Vt = np.linalg.svd(X_scaled)

In [18]:
## array to get delta PC
dbaseline_arr = np.zeros(len(last_date))
dbaseline_arr[1] = dbaseline[0]
dbaseline_arr[6] = dbaseline[1]
dbaseline_arr[8] = dbaseline[2]

dsevadv_arr = np.zeros(len(last_date))
dsevadv_arr[1] = dsevadv[0]
dsevadv_arr[6] = dsevadv[1]
dsevadv_arr[8] = dsevadv[2]

## standarize with X's parameters
dbaseline_arr = (dbaseline_arr - X_mean)/X_sd
dsevadv_arr = (dsevadv_arr - X_mean)/X_sd

## calculate delta PC
dpc_baseline = dbaseline_arr.dot(U[:, :3])
dpc_sevadv = dsevadv_arr.dot(U[:, :3])

## calculate delta y by PCA
dy_baseline = dpc_baseline.dot(U[:, :3].T) * X_sd + X_mean
dy_sevadv = dpc_sevadv.dot(U[:, :3].T) * X_sd + X_mean

## add delta y to 12/31/2019 data to get prediction
pred_baseline_PCA = dy_baseline + last_date
pred_sevadv_PCA = dy_sevadv + last_date

In [19]:
pred_baseline_PCA

array([1.5012548089840898, 1.5690616886180833, 1.6130383239303352,
       1.5972689910177478, 1.5756222181755088, 1.6106611299482587,
       1.6730458441538492, 1.8089100275534125, 1.8973318545717504,
       2.2259364865328664, 2.366181892301054], dtype=object)

In [20]:
pred_sevadv_PCA

array([0.7123992127546557, 1.076160309543409, 1.3326838050923355,
       1.3741284010426962, 1.3882523751580051, 1.3815799153192805,
       1.3759178172906672, 1.4787154751089147, 1.5613964726224845,
       1.8829848073105957, 2.0231629288357844], dtype=object)

## 4. ANN

In [21]:
%load_ext tensorboard
import tensorflow as tf
import tensorflow.keras.backend as kb

In [22]:
dyield_ann = dyield[['Date', '3 MO', '5 YR', '10 YR']]
dyield_ann.columns = ['Date', 'd3 MO', 'd5 YR', 'd10 YR']
X_ann = yield_cleaned.merge(dyield_ann, on = 'Date').iloc[:, 1:].values
Y_ann = dyield.iloc[:, 1:].values
X_ann_mean = np.mean(X_ann, axis = 0)
X_ann_sd = np.std(X_ann, axis = 0)
X_train = preprocessing.scale(X_ann, axis = 0)
Y_train = Y_ann
X_train = tf.convert_to_tensor(X_train)
Y_train = tf.convert_to_tensor(Y_train)
X_pred_baseline = np.hstack([last_date, dbaseline])
X_pred_baseline = (X_pred_baseline - X_ann_mean)/X_ann_sd
X_pred_sevadv = np.hstack([last_date, dsevadv])
X_pred_sevadv = (X_pred_sevadv - X_ann_mean)/X_ann_sd

In [23]:
def custom_loss(y_true, y_pred):
    return kb.sum(kb.square(y_true - y_pred))

## Our neural net
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(14, activation = 'tanh'),
    tf.keras.layers.Dense(16, activation = 'tanh'),
    tf.keras.layers.Dense( 3, activation = 'tanh'),
    tf.keras.layers.Dense(16, activation = 'tanh'),
    tf.keras.layers.Dense(11, activation = 'tanh')
])

## Compile
model.compile(optimizer='adam',
              loss=custom_loss,
              metrics=[custom_loss])

## Specify log storage location
log_dir = "logs\\fit\\" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [24]:
## Cross-val run to find optimal
## Since the logs have been stored, we don't need to rerun this chunk. Check the tensor board below.
#model.fit(X_train, Y_train, validation_split = 0.8, epochs=1000, callbacks=[tensorboard_callback])

In [25]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 119904), started 2:30:46 ago. (Use '!kill 119904' to kill it.)

In [26]:
## Actual training run
model.fit(X_train, Y_train, epochs=500)

Train on 4605 samples
Epoch 1/500
4605/4605 [==============================] - 1s 213us/sample - loss: 3.3407 - custom_loss: 3.3389
Epoch 2/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.5965 - custom_loss: 0.5962
Epoch 3/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.4177 - custom_loss: 0.4176
Epoch 4/500
4605/4605 [==============================] - 0s 66us/sample - loss: 0.3415 - custom_loss: 0.3415
Epoch 5/500
4605/4605 [==============================] - 0s 68us/sample - loss: 0.2902 - custom_loss: 0.2901
Epoch 6/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.2664 - custom_loss: 0.2663
Epoch 7/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.2458 - custom_loss: 0.2457
Epoch 8/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.2292 - custom_loss: 0.2293
Epoch 9/500
4605/4605 [==============================] - 0s 64us/sample - loss: 0.2145 - custom_loss: 0.2

Epoch 75/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.1475 - custom_loss: 0.1475
Epoch 76/500
4605/4605 [==============================] - 0s 78us/sample - loss: 0.1512 - custom_loss: 0.1513
Epoch 77/500
4605/4605 [==============================] - 0s 69us/sample - loss: 0.1502 - custom_loss: 0.1501
Epoch 78/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.1493 - custom_loss: 0.1493
Epoch 79/500
4605/4605 [==============================] - 0s 77us/sample - loss: 0.1495 - custom_loss: 0.1495
Epoch 80/500
4605/4605 [==============================] - 0s 73us/sample - loss: 0.1490 - custom_loss: 0.1490
Epoch 81/500
4605/4605 [==============================] - 0s 74us/sample - loss: 0.1460 - custom_loss: 0.1460
Epoch 82/500
4605/4605 [==============================] - 0s 80us/sample - loss: 0.1486 - custom_loss: 0.1486
Epoch 83/500
4605/4605 [==============================] - 0s 86us/sample - loss: 0.1487 - custom_loss: 0.1486
Epoch 84/5

4605/4605 [==============================] - 0s 61us/sample - loss: 0.1447 - custom_loss: 0.1447
Epoch 149/500
4605/4605 [==============================] - 0s 64us/sample - loss: 0.1442 - custom_loss: 0.1442
Epoch 150/500
4605/4605 [==============================] - 0s 63us/sample - loss: 0.1432 - custom_loss: 0.1437
Epoch 151/500
4605/4605 [==============================] - 0s 65us/sample - loss: 0.1440 - custom_loss: 0.1439
Epoch 152/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.1438 - custom_loss: 0.1438
Epoch 153/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.1443 - custom_loss: 0.1443
Epoch 154/500
4605/4605 [==============================] - 0s 63us/sample - loss: 0.1436 - custom_loss: 0.1436
Epoch 155/500
4605/4605 [==============================] - 0s 63us/sample - loss: 0.1437 - custom_loss: 0.1437
Epoch 156/500
4605/4605 [==============================] - 0s 62us/sample - loss: 0.1443 - custom_loss: 0.1443
Epoch 157/500
4

4605/4605 [==============================] - 0s 68us/sample - loss: 0.1432 - custom_loss: 0.1432
Epoch 222/500
4605/4605 [==============================] - 0s 60us/sample - loss: 0.1423 - custom_loss: 0.1423
Epoch 223/500
4605/4605 [==============================] - 0s 60us/sample - loss: 0.1421 - custom_loss: 0.1422
Epoch 224/500
4605/4605 [==============================] - 0s 65us/sample - loss: 0.1414 - custom_loss: 0.1413
Epoch 225/500
4605/4605 [==============================] - ETA: 0s - loss: 0.1380 - custom_loss: 0.138 - 0s 63us/sample - loss: 0.1428 - custom_loss: 0.1427
Epoch 226/500
4605/4605 [==============================] - 0s 60us/sample - loss: 0.1435 - custom_loss: 0.1435
Epoch 227/500
4605/4605 [==============================] - 0s 60us/sample - loss: 0.1414 - custom_loss: 0.1414
Epoch 228/500
4605/4605 [==============================] - 0s 65us/sample - loss: 0.1412 - custom_loss: 0.1412
Epoch 229/500
4605/4605 [==============================] - 0s 63us/sample - loss

4605/4605 [==============================] - 0s 63us/sample - loss: 0.1401 - custom_loss: 0.1401
Epoch 295/500
4605/4605 [==============================] - 0s 65us/sample - loss: 0.1425 - custom_loss: 0.1425
Epoch 296/500
4605/4605 [==============================] - 0s 66us/sample - loss: 0.1397 - custom_loss: 0.1398
Epoch 297/500
4605/4605 [==============================] - 0s 62us/sample - loss: 0.1411 - custom_loss: 0.1411
Epoch 298/500
4605/4605 [==============================] - 0s 65us/sample - loss: 0.1414 - custom_loss: 0.1414
Epoch 299/500
4605/4605 [==============================] - 0s 64us/sample - loss: 0.1411 - custom_loss: 0.1410
Epoch 300/500
4605/4605 [==============================] - 0s 64us/sample - loss: 0.1414 - custom_loss: 0.1414
Epoch 301/500
4605/4605 [==============================] - 0s 60us/sample - loss: 0.1406 - custom_loss: 0.1406
Epoch 302/500
4605/4605 [==============================] - 0s 59us/sample - loss: 0.1406 - custom_loss: 0.1405
Epoch 303/500
4

Epoch 368/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.1392 - custom_loss: 0.1392
Epoch 369/500
4605/4605 [==============================] - 0s 63us/sample - loss: 0.1408 - custom_loss: 0.14070s - loss: 0.1326 - custom_loss: 0
Epoch 370/500
4605/4605 [==============================] - 0s 64us/sample - loss: 0.1394 - custom_loss: 0.1395
Epoch 371/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.1408 - custom_loss: 0.1408
Epoch 372/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.1409 - custom_loss: 0.1409
Epoch 373/500
4605/4605 [==============================] - 0s 65us/sample - loss: 0.1391 - custom_loss: 0.1391
Epoch 374/500
4605/4605 [==============================] - 0s 64us/sample - loss: 0.1402 - custom_loss: 0.1402
Epoch 375/500
4605/4605 [==============================] - 0s 60us/sample - loss: 0.1386 - custom_loss: 0.1386
Epoch 376/500
4605/4605 [==============================] - 0s 59us/sample - lo

4605/4605 [==============================] - 0s 65us/sample - loss: 0.1389 - custom_loss: 0.1388
Epoch 442/500
4605/4605 [==============================] - 0s 61us/sample - loss: 0.1392 - custom_loss: 0.1391
Epoch 443/500
4605/4605 [==============================] - 0s 65us/sample - loss: 0.1394 - custom_loss: 0.13940s - loss: 0.1370 - custom_loss: 0
Epoch 444/500
4605/4605 [==============================] - 0s 63us/sample - loss: 0.1389 - custom_loss: 0.1389
Epoch 445/500
4605/4605 [==============================] - 0s 59us/sample - loss: 0.1407 - custom_loss: 0.1406
Epoch 446/500
4605/4605 [==============================] - 0s 59us/sample - loss: 0.1399 - custom_loss: 0.1398
Epoch 447/500
4605/4605 [==============================] - 0s 65us/sample - loss: 0.1374 - custom_loss: 0.1374
Epoch 448/500
4605/4605 [==============================] - 0s 69us/sample - loss: 0.1386 - custom_loss: 0.1385
Epoch 449/500
4605/4605 [==============================] - 0s 62us/sample - loss: 0.1391 - c

In [27]:
pred_baseline_ANN = model.predict(X_pred_baseline.reshape(1,-1).astype(np.float32)) + last_date
pred_sevadv_ANN = model.predict(X_pred_sevadv.reshape(1,-1).astype(np.float32)) + last_date

In [28]:
pred_baseline_ANN

array([[1.4907272081077099, 1.572278381511569, 1.6291982330381871,
        1.634473197311163, 1.6426010522246361, 1.6527887758612634,
        1.6793772238865494, 1.749272355735302, 1.7892458122968673,
        2.0956881791353226, 2.2266330713033677]], dtype=object)

In [29]:
pred_sevadv_ANN

array([[0.8685515332221985, 0.9544889807701111, 1.1468633770942689,
        1.1614451670646668, 1.122732059955597, 1.1527492356300355,
        1.2552651786804199, 1.443545298576355, 1.6114218366146087,
        2.026232063770294, 2.1791795337200166]], dtype=object)